language: ruby
cache:
  bundler: true
  directories:
    - "dep_cache"
sudo: false
rvm: 2.4.1
matrix:
  include:
    - rvm: 2.3.4
      env: "RAILS_VERSION=4.2.8"
    - env: "RAILS_VERSION=5.1.1"
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - mkdir -p dep_cache
  - ls -l dep_cache
  - cp config/travis/.solr_wrapper .solr_wrapper
before_script:
  - jdk_switcher use oraclejdk8
