language: ruby
cache: bundler
sudo: false
rvm: 2.4
matrix:
  include:
    - rvm: 2.3
      env: RAILS_VERSION=4.2.10
           BUNDLER_VERSION=1.17.3
    - env: RAILS_VERSION=5.0.7
    - env: RAILS_VERSION=5.1.6
    - rvm: 2.5
    - env: RAILS_VERSION=5.2.1
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - if [ ! -z $BUNDLER_VERSION ]; then gem install bundler -v $BUNDLER_VERSION; else gem install bundler; fi
before_script:
  - jdk_switcher use oraclejdk8
