language: ruby
cache: bundler
sudo: false
rvm: 2.4.1
matrix:
  include:
    - rvm: 2.3.4
      env: "RAILS_VERSION=4.2.10"
    - env: "RAILS_VERSION=5.1.1"
    - rvm: 2.5.1
      env: RAILS_VERSION=5.2.0
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - jdk_switcher use oraclejdk8
